# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CustomerBillingAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, v_flat_number: str=None, v_address_line1: str=None, v_address_line2: str=None, v_land_mark: str=None, v_state: str=None, v_city: str=None, v_pin_code: str=None, dt_created: datetime=None, dt_updated: datetime=None):  # noqa: E501
        """CustomerBillingAddress - a model defined in Swagger

        :param id: The id of this CustomerBillingAddress.  # noqa: E501
        :type id: int
        :param v_flat_number: The v_flat_number of this CustomerBillingAddress.  # noqa: E501
        :type v_flat_number: str
        :param v_address_line1: The v_address_line1 of this CustomerBillingAddress.  # noqa: E501
        :type v_address_line1: str
        :param v_address_line2: The v_address_line2 of this CustomerBillingAddress.  # noqa: E501
        :type v_address_line2: str
        :param v_land_mark: The v_land_mark of this CustomerBillingAddress.  # noqa: E501
        :type v_land_mark: str
        :param v_state: The v_state of this CustomerBillingAddress.  # noqa: E501
        :type v_state: str
        :param v_city: The v_city of this CustomerBillingAddress.  # noqa: E501
        :type v_city: str
        :param v_pin_code: The v_pin_code of this CustomerBillingAddress.  # noqa: E501
        :type v_pin_code: str
        :param dt_created: The dt_created of this CustomerBillingAddress.  # noqa: E501
        :type dt_created: datetime
        :param dt_updated: The dt_updated of this CustomerBillingAddress.  # noqa: E501
        :type dt_updated: datetime
        """
        self.swagger_types = {
            'id': int,
            'v_flat_number': str,
            'v_address_line1': str,
            'v_address_line2': str,
            'v_land_mark': str,
            'v_state': str,
            'v_city': str,
            'v_pin_code': str,
            'dt_created': datetime,
            'dt_updated': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'v_flat_number': 'vFlatNumber',
            'v_address_line1': 'vAddressLine1',
            'v_address_line2': 'vAddressLine2',
            'v_land_mark': 'vLandMark',
            'v_state': 'vState',
            'v_city': 'vCity',
            'v_pin_code': 'vPinCode',
            'dt_created': 'dtCreated',
            'dt_updated': 'dtUpdated'
        }

        self._id = id
        self._v_flat_number = v_flat_number
        self._v_address_line1 = v_address_line1
        self._v_address_line2 = v_address_line2
        self._v_land_mark = v_land_mark
        self._v_state = v_state
        self._v_city = v_city
        self._v_pin_code = v_pin_code
        self._dt_created = dt_created
        self._dt_updated = dt_updated

    @classmethod
    def from_dict(cls, dikt) -> 'CustomerBillingAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The customer_billing_address of this CustomerBillingAddress.  # noqa: E501
        :rtype: CustomerBillingAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this CustomerBillingAddress.


        :return: The id of this CustomerBillingAddress.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this CustomerBillingAddress.


        :param id: The id of this CustomerBillingAddress.
        :type id: int
        """

        self._id = id

    @property
    def v_flat_number(self) -> str:
        """Gets the v_flat_number of this CustomerBillingAddress.


        :return: The v_flat_number of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_flat_number

    @v_flat_number.setter
    def v_flat_number(self, v_flat_number: str):
        """Sets the v_flat_number of this CustomerBillingAddress.


        :param v_flat_number: The v_flat_number of this CustomerBillingAddress.
        :type v_flat_number: str
        """

        self._v_flat_number = v_flat_number

    @property
    def v_address_line1(self) -> str:
        """Gets the v_address_line1 of this CustomerBillingAddress.


        :return: The v_address_line1 of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_address_line1

    @v_address_line1.setter
    def v_address_line1(self, v_address_line1: str):
        """Sets the v_address_line1 of this CustomerBillingAddress.


        :param v_address_line1: The v_address_line1 of this CustomerBillingAddress.
        :type v_address_line1: str
        """

        self._v_address_line1 = v_address_line1

    @property
    def v_address_line2(self) -> str:
        """Gets the v_address_line2 of this CustomerBillingAddress.


        :return: The v_address_line2 of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_address_line2

    @v_address_line2.setter
    def v_address_line2(self, v_address_line2: str):
        """Sets the v_address_line2 of this CustomerBillingAddress.


        :param v_address_line2: The v_address_line2 of this CustomerBillingAddress.
        :type v_address_line2: str
        """

        self._v_address_line2 = v_address_line2

    @property
    def v_land_mark(self) -> str:
        """Gets the v_land_mark of this CustomerBillingAddress.


        :return: The v_land_mark of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_land_mark

    @v_land_mark.setter
    def v_land_mark(self, v_land_mark: str):
        """Sets the v_land_mark of this CustomerBillingAddress.


        :param v_land_mark: The v_land_mark of this CustomerBillingAddress.
        :type v_land_mark: str
        """

        self._v_land_mark = v_land_mark

    @property
    def v_state(self) -> str:
        """Gets the v_state of this CustomerBillingAddress.


        :return: The v_state of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_state

    @v_state.setter
    def v_state(self, v_state: str):
        """Sets the v_state of this CustomerBillingAddress.


        :param v_state: The v_state of this CustomerBillingAddress.
        :type v_state: str
        """

        self._v_state = v_state

    @property
    def v_city(self) -> str:
        """Gets the v_city of this CustomerBillingAddress.


        :return: The v_city of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_city

    @v_city.setter
    def v_city(self, v_city: str):
        """Sets the v_city of this CustomerBillingAddress.


        :param v_city: The v_city of this CustomerBillingAddress.
        :type v_city: str
        """

        self._v_city = v_city

    @property
    def v_pin_code(self) -> str:
        """Gets the v_pin_code of this CustomerBillingAddress.


        :return: The v_pin_code of this CustomerBillingAddress.
        :rtype: str
        """
        return self._v_pin_code

    @v_pin_code.setter
    def v_pin_code(self, v_pin_code: str):
        """Sets the v_pin_code of this CustomerBillingAddress.


        :param v_pin_code: The v_pin_code of this CustomerBillingAddress.
        :type v_pin_code: str
        """

        self._v_pin_code = v_pin_code

    @property
    def dt_created(self) -> datetime:
        """Gets the dt_created of this CustomerBillingAddress.


        :return: The dt_created of this CustomerBillingAddress.
        :rtype: datetime
        """
        return self._dt_created

    @dt_created.setter
    def dt_created(self, dt_created: datetime):
        """Sets the dt_created of this CustomerBillingAddress.


        :param dt_created: The dt_created of this CustomerBillingAddress.
        :type dt_created: datetime
        """

        self._dt_created = dt_created

    @property
    def dt_updated(self) -> datetime:
        """Gets the dt_updated of this CustomerBillingAddress.


        :return: The dt_updated of this CustomerBillingAddress.
        :rtype: datetime
        """
        return self._dt_updated

    @dt_updated.setter
    def dt_updated(self, dt_updated: datetime):
        """Sets the dt_updated of this CustomerBillingAddress.


        :param dt_updated: The dt_updated of this CustomerBillingAddress.
        :type dt_updated: datetime
        """

        self._dt_updated = dt_updated
