# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CustomerCategory(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, i_cat_id: int=None, v_category_name: str=None, dt_created: datetime=None, dt_updated: datetime=None):  # noqa: E501
        """CustomerCategory - a model defined in Swagger

        :param i_cat_id: The i_cat_id of this CustomerCategory.  # noqa: E501
        :type i_cat_id: int
        :param v_category_name: The v_category_name of this CustomerCategory.  # noqa: E501
        :type v_category_name: str
        :param dt_created: The dt_created of this CustomerCategory.  # noqa: E501
        :type dt_created: datetime
        :param dt_updated: The dt_updated of this CustomerCategory.  # noqa: E501
        :type dt_updated: datetime
        """
        self.swagger_types = {
            'i_cat_id': int,
            'v_category_name': str,
            'dt_created': datetime,
            'dt_updated': datetime
        }

        self.attribute_map = {
            'i_cat_id': 'iCatId',
            'v_category_name': 'vCategoryName',
            'dt_created': 'dtCreated',
            'dt_updated': 'dtUpdated'
        }

        self._i_cat_id = i_cat_id
        self._v_category_name = v_category_name
        self._dt_created = dt_created
        self._dt_updated = dt_updated

    @classmethod
    def from_dict(cls, dikt) -> 'CustomerCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The customer_category of this CustomerCategory.  # noqa: E501
        :rtype: CustomerCategory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def i_cat_id(self) -> int:
        """Gets the i_cat_id of this CustomerCategory.


        :return: The i_cat_id of this CustomerCategory.
        :rtype: int
        """
        return self._i_cat_id

    @i_cat_id.setter
    def i_cat_id(self, i_cat_id: int):
        """Sets the i_cat_id of this CustomerCategory.


        :param i_cat_id: The i_cat_id of this CustomerCategory.
        :type i_cat_id: int
        """

        self._i_cat_id = i_cat_id

    @property
    def v_category_name(self) -> str:
        """Gets the v_category_name of this CustomerCategory.


        :return: The v_category_name of this CustomerCategory.
        :rtype: str
        """
        return self._v_category_name

    @v_category_name.setter
    def v_category_name(self, v_category_name: str):
        """Sets the v_category_name of this CustomerCategory.


        :param v_category_name: The v_category_name of this CustomerCategory.
        :type v_category_name: str
        """

        self._v_category_name = v_category_name

    @property
    def dt_created(self) -> datetime:
        """Gets the dt_created of this CustomerCategory.


        :return: The dt_created of this CustomerCategory.
        :rtype: datetime
        """
        return self._dt_created

    @dt_created.setter
    def dt_created(self, dt_created: datetime):
        """Sets the dt_created of this CustomerCategory.


        :param dt_created: The dt_created of this CustomerCategory.
        :type dt_created: datetime
        """

        self._dt_created = dt_created

    @property
    def dt_updated(self) -> datetime:
        """Gets the dt_updated of this CustomerCategory.


        :return: The dt_updated of this CustomerCategory.
        :rtype: datetime
        """
        return self._dt_updated

    @dt_updated.setter
    def dt_updated(self, dt_updated: datetime):
        """Sets the dt_updated of this CustomerCategory.


        :param dt_updated: The dt_updated of this CustomerCategory.
        :type dt_updated: datetime
        """

        self._dt_updated = dt_updated
