# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Dummy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, dummy: str=None):  # noqa: E501
        """Dummy - a model defined in Swagger

        :param dummy: The dummy of this Dummy.  # noqa: E501
        :type dummy: str
        """
        self.swagger_types = {
            'dummy': str
        }

        self.attribute_map = {
            'dummy': 'dummy'
        }

        self._dummy = dummy

    @classmethod
    def from_dict(cls, dikt) -> 'Dummy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dummy of this Dummy.  # noqa: E501
        :rtype: Dummy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dummy(self) -> str:
        """Gets the dummy of this Dummy.

        dummy object  # noqa: E501

        :return: The dummy of this Dummy.
        :rtype: str
        """
        return self._dummy

    @dummy.setter
    def dummy(self, dummy: str):
        """Sets the dummy of this Dummy.

        dummy object  # noqa: E501

        :param dummy: The dummy of this Dummy.
        :type dummy: str
        """
        if dummy is None:
            raise ValueError("Invalid value for `dummy`, must not be `None`")  # noqa: E501

        self._dummy = dummy
