# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InvoiceItemBillingCycle(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, i_cycle_id: int=None, v_cycle_name: str=None, i_cycle_days: int=None, i_cycle_month: int=None):  # noqa: E501
        """InvoiceItemBillingCycle - a model defined in Swagger

        :param i_cycle_id: The i_cycle_id of this InvoiceItemBillingCycle.  # noqa: E501
        :type i_cycle_id: int
        :param v_cycle_name: The v_cycle_name of this InvoiceItemBillingCycle.  # noqa: E501
        :type v_cycle_name: str
        :param i_cycle_days: The i_cycle_days of this InvoiceItemBillingCycle.  # noqa: E501
        :type i_cycle_days: int
        :param i_cycle_month: The i_cycle_month of this InvoiceItemBillingCycle.  # noqa: E501
        :type i_cycle_month: int
        """
        self.swagger_types = {
            'i_cycle_id': int,
            'v_cycle_name': str,
            'i_cycle_days': int,
            'i_cycle_month': int
        }

        self.attribute_map = {
            'i_cycle_id': 'iCycleId',
            'v_cycle_name': 'vCycleName',
            'i_cycle_days': 'iCycleDays',
            'i_cycle_month': 'iCycleMonth'
        }

        self._i_cycle_id = i_cycle_id
        self._v_cycle_name = v_cycle_name
        self._i_cycle_days = i_cycle_days
        self._i_cycle_month = i_cycle_month

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceItemBillingCycle':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The invoice_item_billing_cycle of this InvoiceItemBillingCycle.  # noqa: E501
        :rtype: InvoiceItemBillingCycle
        """
        return util.deserialize_model(dikt, cls)

    @property
    def i_cycle_id(self) -> int:
        """Gets the i_cycle_id of this InvoiceItemBillingCycle.


        :return: The i_cycle_id of this InvoiceItemBillingCycle.
        :rtype: int
        """
        return self._i_cycle_id

    @i_cycle_id.setter
    def i_cycle_id(self, i_cycle_id: int):
        """Sets the i_cycle_id of this InvoiceItemBillingCycle.


        :param i_cycle_id: The i_cycle_id of this InvoiceItemBillingCycle.
        :type i_cycle_id: int
        """

        self._i_cycle_id = i_cycle_id

    @property
    def v_cycle_name(self) -> str:
        """Gets the v_cycle_name of this InvoiceItemBillingCycle.


        :return: The v_cycle_name of this InvoiceItemBillingCycle.
        :rtype: str
        """
        return self._v_cycle_name

    @v_cycle_name.setter
    def v_cycle_name(self, v_cycle_name: str):
        """Sets the v_cycle_name of this InvoiceItemBillingCycle.


        :param v_cycle_name: The v_cycle_name of this InvoiceItemBillingCycle.
        :type v_cycle_name: str
        """

        self._v_cycle_name = v_cycle_name

    @property
    def i_cycle_days(self) -> int:
        """Gets the i_cycle_days of this InvoiceItemBillingCycle.


        :return: The i_cycle_days of this InvoiceItemBillingCycle.
        :rtype: int
        """
        return self._i_cycle_days

    @i_cycle_days.setter
    def i_cycle_days(self, i_cycle_days: int):
        """Sets the i_cycle_days of this InvoiceItemBillingCycle.


        :param i_cycle_days: The i_cycle_days of this InvoiceItemBillingCycle.
        :type i_cycle_days: int
        """

        self._i_cycle_days = i_cycle_days

    @property
    def i_cycle_month(self) -> int:
        """Gets the i_cycle_month of this InvoiceItemBillingCycle.


        :return: The i_cycle_month of this InvoiceItemBillingCycle.
        :rtype: int
        """
        return self._i_cycle_month

    @i_cycle_month.setter
    def i_cycle_month(self, i_cycle_month: int):
        """Sets the i_cycle_month of this InvoiceItemBillingCycle.


        :param i_cycle_month: The i_cycle_month of this InvoiceItemBillingCycle.
        :type i_cycle_month: int
        """

        self._i_cycle_month = i_cycle_month
