# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InvoiceBrand(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, v_brand_name: str=None, v_brand_logo: str=None, v_brand_tax_info: str=None, v_bran_contact_info: str=None, v_brand_payment_info: str=None):  # noqa: E501
        """InvoiceBrand - a model defined in Swagger

        :param v_brand_name: The v_brand_name of this InvoiceBrand.  # noqa: E501
        :type v_brand_name: str
        :param v_brand_logo: The v_brand_logo of this InvoiceBrand.  # noqa: E501
        :type v_brand_logo: str
        :param v_brand_tax_info: The v_brand_tax_info of this InvoiceBrand.  # noqa: E501
        :type v_brand_tax_info: str
        :param v_bran_contact_info: The v_bran_contact_info of this InvoiceBrand.  # noqa: E501
        :type v_bran_contact_info: str
        :param v_brand_payment_info: The v_brand_payment_info of this InvoiceBrand.  # noqa: E501
        :type v_brand_payment_info: str
        """
        self.swagger_types = {
            'v_brand_name': str,
            'v_brand_logo': str,
            'v_brand_tax_info': str,
            'v_bran_contact_info': str,
            'v_brand_payment_info': str
        }

        self.attribute_map = {
            'v_brand_name': 'vBrandName',
            'v_brand_logo': 'vBrandLogo',
            'v_brand_tax_info': 'vBrandTaxInfo',
            'v_bran_contact_info': 'vBranContactInfo',
            'v_brand_payment_info': 'vBrandPaymentInfo'
        }

        self._v_brand_name = v_brand_name
        self._v_brand_logo = v_brand_logo
        self._v_brand_tax_info = v_brand_tax_info
        self._v_bran_contact_info = v_bran_contact_info
        self._v_brand_payment_info = v_brand_payment_info

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceBrand':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The invoice_brand of this InvoiceBrand.  # noqa: E501
        :rtype: InvoiceBrand
        """
        return util.deserialize_model(dikt, cls)

    @property
    def v_brand_name(self) -> str:
        """Gets the v_brand_name of this InvoiceBrand.


        :return: The v_brand_name of this InvoiceBrand.
        :rtype: str
        """
        return self._v_brand_name

    @v_brand_name.setter
    def v_brand_name(self, v_brand_name: str):
        """Sets the v_brand_name of this InvoiceBrand.


        :param v_brand_name: The v_brand_name of this InvoiceBrand.
        :type v_brand_name: str
        """

        self._v_brand_name = v_brand_name

    @property
    def v_brand_logo(self) -> str:
        """Gets the v_brand_logo of this InvoiceBrand.


        :return: The v_brand_logo of this InvoiceBrand.
        :rtype: str
        """
        return self._v_brand_logo

    @v_brand_logo.setter
    def v_brand_logo(self, v_brand_logo: str):
        """Sets the v_brand_logo of this InvoiceBrand.


        :param v_brand_logo: The v_brand_logo of this InvoiceBrand.
        :type v_brand_logo: str
        """

        self._v_brand_logo = v_brand_logo

    @property
    def v_brand_tax_info(self) -> str:
        """Gets the v_brand_tax_info of this InvoiceBrand.


        :return: The v_brand_tax_info of this InvoiceBrand.
        :rtype: str
        """
        return self._v_brand_tax_info

    @v_brand_tax_info.setter
    def v_brand_tax_info(self, v_brand_tax_info: str):
        """Sets the v_brand_tax_info of this InvoiceBrand.


        :param v_brand_tax_info: The v_brand_tax_info of this InvoiceBrand.
        :type v_brand_tax_info: str
        """

        self._v_brand_tax_info = v_brand_tax_info

    @property
    def v_bran_contact_info(self) -> str:
        """Gets the v_bran_contact_info of this InvoiceBrand.


        :return: The v_bran_contact_info of this InvoiceBrand.
        :rtype: str
        """
        return self._v_bran_contact_info

    @v_bran_contact_info.setter
    def v_bran_contact_info(self, v_bran_contact_info: str):
        """Sets the v_bran_contact_info of this InvoiceBrand.


        :param v_bran_contact_info: The v_bran_contact_info of this InvoiceBrand.
        :type v_bran_contact_info: str
        """

        self._v_bran_contact_info = v_bran_contact_info

    @property
    def v_brand_payment_info(self) -> str:
        """Gets the v_brand_payment_info of this InvoiceBrand.


        :return: The v_brand_payment_info of this InvoiceBrand.
        :rtype: str
        """
        return self._v_brand_payment_info

    @v_brand_payment_info.setter
    def v_brand_payment_info(self, v_brand_payment_info: str):
        """Sets the v_brand_payment_info of this InvoiceBrand.


        :param v_brand_payment_info: The v_brand_payment_info of this InvoiceBrand.
        :type v_brand_payment_info: str
        """

        self._v_brand_payment_info = v_brand_payment_info
